export const machineGpByHosp = [
    {
        label: 'CCH', 
        options: [
            { label : "CMS-IP", value : "CMS-IP", hospCode : "CCH"},
            { label : "UNKNOWN", value : "UNKNOWN", hospCode : "CCH"},
            { label : "PILOT_WKS", value : "PILOT_WKS", hospCode : "CCH"},
            { label : "TOUGHPAD", value : "TOUGHPAD", hospCode : "CCH"},
            { label : "CMS-SRE", value : "CMS-SRE", hospCode : "CCH"},
            { label : "IPMOE_BDS_OFFLINE_MAR", value : "IPMOE_BDS_OFFLINE_MAR", hospCode : "CCH"},
            { label : "CRAS-WKS", value : "CRAS-WKS", hospCode : "CCH"},
            { label : "IPMOE-DEMO-WS", value : "IPMOE-DEMO-WS", hospCode : "CCH"},
            { label : "AAT-TEST-WS", value : "AAT-TEST-WS", hospCode : "CCH"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "CCH"},
            { label : "TOUGHPAD-W11", value : "TOUGHPAD-W11", hospCode : "CCH"},
        ],
        index : 0,
    },
    {
        label: 'PYN', 
        options: [
            { label : "CMS-IP", value : "CMS-IP", hospCode : "PYN"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "PYN"},
            { label : "ERS-CID", value : "ERS-CID", hospCode : "PYN"},
            { label : "AEIS-WEB", value : "AEIS-WEB", hospCode : "PYN"},
            { label : "PILOT_WKS", value : "PILOT_WKS", hospCode : "PYN"},
            { label : "CRAS-WKS", value : "CRAS-WKS", hospCode : "PYN"},
            { label : "IVM-LINK", value : "IVM-LINK", hospCode : "PYN"},
            { label : "CMS-OPEN", value : "CMS-OPEN", hospCode : "PYN"},
            { label : "PAS-INT", value : "PAS-INT", hospCode : "PYN"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "PYN"},
            { label : "IPMOE_BDS_OFFLINE_MAR", value : "IPMOE_BDS_OFFLINE_MAR", hospCode : "PYN"},
            { label : "TOUGHPAD", value : "TOUGHPAD", hospCode : "PYN"},
            { label : "AEIS-INT", value : "AEIS-INT", hospCode : "PYN"},
            { label : "CVIS-ISCV-LINK", value : "CVIS-ISCV-LINK", hospCode : "PYN"},
            { label : "FAST_LOGON", value : "FAST_LOGON", hospCode : "PYN"},
            { label : "ICU-CIS-Chrome", value : "ICU-CIS-Chrome", hospCode : "PYN"},
            { label : "PNICU-CIS-Chrome", value : "PNICU-CIS-Chrome", hospCode : "PYN"},
            { label : "CQMS_driect_call", value : "CQMS_driect_call", hospCode : "PYN"},
            { label : "CQMS-AED", value : "CQMS-AED", hospCode : "PYN"},
            { label : "CQMS_Chrome", value : "CQMS_Chrome", hospCode : "PYN"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "PYN"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "PYN"},
            { label : "TOUGHPAD-W11", value : "TOUGHPAD-W11", hospCode : "PYN"},
        ],
        index : 1,
    },
    {
        label: 'RH', 
        options: [
            { label : "CMS-IP", value : "CMS-IP", hospCode : "RH"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "RH"},
            { label : "AEIS-WEB", value : "AEIS-WEB", hospCode : "RH"},
            { label : "PILOT_WKS", value : "PILOT_WKS", hospCode : "RH"},
            { label : "GCR-TEST", value : "GCR-TEST", hospCode : "RH"},
            { label : "RIS-INT", value : "RIS-INT", hospCode : "RH"},
            { label : "CRAS", value : "CRAS", hospCode : "RH"},
            { label : "PAS-INT", value : "PAS-INT", hospCode : "RH"},
            { label : "CMS-SRE", value : "CMS-SRE", hospCode : "RH"},
            { label : "ERS-CID", value : "ERS-CID", hospCode : "RH"},
            { label : "UNKNOWN", value : "UNKNOWN", hospCode : "RH"},
            { label : "SOPD", value : "SOPD", hospCode : "RH"},
            { label : "TOUGHPAD", value : "TOUGHPAD", hospCode : "RH"},
            { label : "CQMS", value : "CQMS", hospCode : "RH"},
            { label : "NB_DRUG_ADMIN", value : "NB_DRUG_ADMIN", hospCode : "RH"},
            { label : "AEIS-INT", value : "AEIS-INT", hospCode : "RH"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "RH"},
            { label : "IPMOE_BDS_OFFLINE_MAR", value : "IPMOE_BDS_OFFLINE_MAR", hospCode : "RH"},
            { label : "CQMS-AED", value : "CQMS-AED", hospCode : "RH"},
            { label : "FAST_LOGON", value : "FAST_LOGON", hospCode : "RH"},
            { label : "PAS-FONT-TEMP", value : "PAS-FONT-TEMP", hospCode : "RH"},
            { label : "WINS-WKS", value : "WINS-WKS", hospCode : "RH"},
            { label : "CQMS_Chrome", value : "CQMS_Chrome", hospCode : "RH"},
            { label : "FIX-MDE", value : "FIX-MDE", hospCode : "RH"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "RH"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "RH"},
            { label : "TOUGHPAD-W11", value : "TOUGHPAD-W11", hospCode : "RH"},
        ],
        index : 2,
    },
    {
        label: 'SJH', 
        options: [
            { label : "CMS-IP", value : "CMS-IP", hospCode : "SJH"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "SJH"},
            { label : "AEIS-INT", value : "AEIS-INT", hospCode : "SJH"},
            { label : "UNKNOWN", value : "UNKNOWN", hospCode : "SJH"},
            { label : "CRAS-WKS", value : "CRAS-WKS", hospCode : "SJH"},
            { label : "PILOT_WKS", value : "PILOT_WKS", hospCode : "SJH"},
            { label : "TOUGHPAD", value : "TOUGHPAD", hospCode : "SJH"},
            { label : "CMS-SRE", value : "CMS-SRE", hospCode : "SJH"},
            { label : "IPMOE_BDS_OFFLINE_MAR", value : "IPMOE_BDS_OFFLINE_MAR", hospCode : "SJH"},
            { label : "FAST_LOGON", value : "FAST_LOGON", hospCode : "SJH"},
            { label : "CQMS-AED", value : "CQMS-AED", hospCode : "SJH"},
            { label : "CQMS_Chrome", value : "CQMS_Chrome", hospCode : "SJH"},
            { label : "AAT-TEST-WS", value : "AAT-TEST-WS", hospCode : "SJH"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "SJH"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "SJH"},
            { label : "TOUGHPAD-W11", value : "TOUGHPAD-W11", hospCode : "SJH"},
        ],
        index : 3,
    },
    {
        label: 'TWE', 
        options: [
            { label : "CMS-IP", value : "CMS-IP", hospCode : "TWE"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "TWE"},
            { label : "CMS-SRE", value : "CMS-SRE", hospCode : "TWE"},
            { label : "PILOT_WKS", value : "PILOT_WKS", hospCode : "TWE"},
            { label : "TOUGHPAD", value : "TOUGHPAD", hospCode : "TWE"},
            { label : "IPMOE_BDS_OFFLINE_MAR", value : "IPMOE_BDS_OFFLINE_MAR", hospCode : "TWE"},
            { label : "CQMS", value : "CQMS", hospCode : "TWE"},
            { label : "CRAS-WKS", value : "CRAS-WKS", hospCode : "TWE"},
            { label : "CQMS_Chrome", value : "CQMS_Chrome", hospCode : "TWE"},
            { label : "FIX-MDE", value : "FIX-MDE", hospCode : "TWE"},
            { label : "IPMOE-DEMO-WS", value : "IPMOE-DEMO-WS", hospCode : "TWE"},
            { label : "AAT-TEST-WS", value : "AAT-TEST-WS", hospCode : "TWE"},
            { label : "PILOT-SCREEN-SAVER", value : "PILOT-SCREEN-SAVER", hospCode : "TWE"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "TWE"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "TWE"},
            { label : "TOUGHPAD-W11", value : "TOUGHPAD-W11", hospCode : "TWE"},
        ],
        index : 4,
    },
    {
        label: 'WCH', 
        options: [
            { label : "CMS-IP", value : "CMS-IP", hospCode : "WCH"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "WCH"},
            { label : "PILOT_WKS", value : "PILOT_WKS", hospCode : "WCH"},
            { label : "TOUGHPAD", value : "TOUGHPAD", hospCode : "WCH"},
            { label : "CMS-SRE", value : "CMS-SRE", hospCode : "WCH"},
            { label : "IPMOE_BDS_OFFLINE_MAR", value : "IPMOE_BDS_OFFLINE_MAR", hospCode : "WCH"},
            { label : "CRAS-WKS", value : "CRAS-WKS", hospCode : "WCH"},
            { label : "IPMOE-DEMO-WS", value : "IPMOE-DEMO-WS", hospCode : "WCH"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "WCH"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "WCH"},
            { label : "TOUGHPAD-W11", value : "TOUGHPAD-W11", hospCode : "WCH"},
        ],
        index : 5,
    },
    {
        label: 'KCH', 
        options: [
            { label : "CMS-OPAS", value : "CMS-OPAS", hospCode : "KCH"},
            { label : "INT-OPAS", value : "INT-OPAS", hospCode : "KCH"},
            { label : "GCRSRE_PRINT", value : "GCRSRE_PRINT", hospCode : "KCH"},
            { label : "WIN7", value : "WIN7", hospCode : "KCH"},
            { label : "web_rollback", value : "web_rollback", hospCode : "KCH"},
            { label : "open_web_cms", value : "open_web_cms", hospCode : "KCH"},
            { label : "WIN10", value : "WIN10", hospCode : "KCH"},
            { label : "WIN10_OPEN", value : "WIN10_OPEN", hospCode : "KCH"},
            { label : "SCRNSAVE_OFF", value : "SCRNSAVE_OFF", hospCode : "KCH"},
            { label : "CQMS_startup", value : "CQMS_startup", hospCode : "KCH"},
            { label : "EDGE_FILMLESS", value : "EDGE_FILMLESS", hospCode : "KCH"},
            { label : "cms_screen_config", value : "cms_screen_config", hospCode : "KCH"},
            { label : "check_ipmoe_iis", value : "check_ipmoe_iis", hospCode : "KCH"},
            { label : "WIN7_JAVA18", value : "WIN7_JAVA18", hospCode : "KCH"},
            { label : "check_cras_java", value : "check_cras_java", hospCode : "KCH"},
            { label : "ccp190", value : "ccp190", hospCode : "KCH"},
            { label : "cmschrome", value : "cmschrome", hospCode : "KCH"},
            { label : "TOUGHPAD-W10", value : "TOUGHPAD-W10", hospCode : "KCH"},
            { label : "MDE_WKS", value : "MDE_WKS", hospCode : "KCH"},
            { label : "MDE_WKS_BK", value : "MDE_WKS_BK", hospCode : "KCH"},
            { label : "IP-MOE-MAR", value : "IP-MOE-MAR", hospCode : "KCH"},
            { label : "BDS_WKS", value : "BDS_WKS", hospCode : "KCH"},
        ],
        index : 6,
    },
    {
        label: 'CMC', 
        options: [
            { label : "EOT-GP", value : "EOT-GP", hospCode : "CMC"},
            { label : "OTMS-GP", value : "OTMS-GP", hospCode : "CMC"},
            { label : "CMC-FM", value : "CMC-FM", hospCode : "CMC"},
            { label : "CMS-SKM", value : "CMS-SKM", hospCode : "CMC"},
            { label : "CMS-WKG", value : "CMS-WKG", hospCode : "CMC"},
            { label : "CMS-NSG", value : "CMS-NSG", hospCode : "CMC"},
            { label : "CMS-CSW", value : "CMS-CSW", hospCode : "CMC"},
            { label : "CMS-NCG", value : "CMS-NCG", hospCode : "CMC"},
            { label : "WINXP-AE", value : "WINXP-AE", hospCode : "CMC"},
            { label : "AEIS_WEB_GP", value : "AEIS_WEB_GP", hospCode : "CMC"},
            { label : "GCRSRE_PRINT", value : "GCRSRE_PRINT", hospCode : "CMC"},
            { label : "FILMLESS-EXT", value : "FILMLESS-EXT", hospCode : "CMC"},
            { label : "WIN7", value : "WIN7", hospCode : "CMC"},
            { label : "OPD-AE", value : "OPD-AE", hospCode : "CMC"},
            { label : "NEW_CRAS", value : "NEW_CRAS", hospCode : "CMC"},
            { label : "CRAS_JAVA", value : "CRAS_JAVA", hospCode : "CMC"},
            { label : "CID_WKS", value : "CID_WKS", hospCode : "CMC"},
            { label : "open_web_cms", value : "open_web_cms", hospCode : "CMC"},
            { label : "IPMOE_BACKUP", value : "IPMOE_BACKUP", hospCode : "CMC"},
            { label : "IP_MOE_G1", value : "IP_MOE_G1", hospCode : "CMC"},
            { label : "BDS_WKS", value : "BDS_WKS", hospCode : "CMC"},
            { label : "IPMOE_OFFLINE", value : "IPMOE_OFFLINE", hospCode : "CMC"},
            { label : "GREEN_PWR_WKS", value : "GREEN_PWR_WKS", hospCode : "CMC"},
            { label : "logoff_reminder_ie", value : "logoff_reminder_ie", hospCode : "CMC"},
            { label : "mon_off_wks", value : "mon_off_wks", hospCode : "CMC"},
            { label : "WIN10", value : "WIN10", hospCode : "CMC"},
            { label : "WIN10_OPEN", value : "WIN10_OPEN", hospCode : "CMC"},
            { label : "SOPD-MEM", value : "SOPD-MEM", hospCode : "CMC"},
            { label : "TOUGHPAD-W10", value : "TOUGHPAD-W10", hospCode : "CMC"},
            { label : "AE_90TIMEOUT", value : "AE_90TIMEOUT", hospCode : "CMC"},
            { label : "CQMS_WKS", value : "CQMS_WKS", hospCode : "CMC"},
            { label : "CQMS_startup", value : "CQMS_startup", hospCode : "CMC"},
            { label : "EDGE_FILMLESS", value : "EDGE_FILMLESS", hospCode : "CMC"},
            { label : "cms_screen_config", value : "cms_screen_config", hospCode : "CMC"},
            { label : "offline_mar", value : "offline_mar", hospCode : "CMC"},
            { label : "check_ipmoe_iis", value : "check_ipmoe_iis", hospCode : "CMC"},
            { label : "WIN7_JAVA18", value : "WIN7_JAVA18", hospCode : "CMC"},
            { label : "check_cras_java", value : "check_cras_java", hospCode : "CMC"},
            { label : "VTS_wks", value : "VTS_wks", hospCode : "CMC"},
            { label : "inst_AEIS_web_12c", value : "inst_AEIS_web_12c", hospCode : "CMC"},
            { label : "scr_dist_jar", value : "scr_dist_jar", hospCode : "CMC"},
            { label : "install_chrome", value : "install_chrome", hospCode : "CMC"},
            { label : "ccp190", value : "ccp190", hospCode : "CMC"},
            { label : "ICU_CIS_link", value : "ICU_CIS_link", hospCode : "CMC"},
            { label : "win10_jre6", value : "win10_jre6", hospCode : "CMC"},
            { label : "cmschrome", value : "cmschrome", hospCode : "CMC"},
            { label : "CLW_OT", value : "CLW_OT", hospCode : "CMC"},
            { label : "OTPIS_OT", value : "OTPIS_OT", hospCode : "CMC"},
            { label : "CHROME_CQMS", value : "CHROME_CQMS", hospCode : "CMC"},
            { label : "ACIS_WKS", value : "ACIS_WKS", hospCode : "CMC"},
            { label : "MDE_WKS", value : "MDE_WKS", hospCode : "CMC"},
            { label : "MDE_WKS_BK", value : "MDE_WKS_BK", hospCode : "CMC"},
            { label : "E-DISPLAY", value : "E-DISPLAY", hospCode : "CMC"},
            { label : "Annalise_ailink", value : "Annalise_ailink", hospCode : "CMC"},
            { label : "PNIS_GROUP", value : "PNIS_GROUP", hospCode : "CMC"},
        ],
        index : 7,
    },
    {
        label: 'NLT', 
        options: [
            { label : "AEIS", value : "AEIS", hospCode : "NLT"},
            { label : "GCRSRE_PRINT", value : "GCRSRE_PRINT", hospCode : "NLT"},
            { label : "NLT-FM", value : "NLT-FM", hospCode : "NLT"},
            { label : "SOPD", value : "SOPD", hospCode : "NLT"},
            { label : "WIN7", value : "WIN7", hospCode : "NLT"},
            { label : "CMS-MWG", value : "CMS-MWG", hospCode : "NLT"},
            { label : "CMS-TOJ", value : "CMS-TOJ", hospCode : "NLT"},
            { label : "testing_HAHO", value : "testing_HAHO", hospCode : "NLT"},
            { label : "ipmoe_toughpad", value : "ipmoe_toughpad", hospCode : "NLT"},
            { label : "BDS_WKS", value : "BDS_WKS", hospCode : "NLT"},
            { label : "ip_moe_mar", value : "ip_moe_mar", hospCode : "NLT"},
            { label : "web_rollback", value : "web_rollback", hospCode : "NLT"},
            { label : "eot_group", value : "eot_group", hospCode : "NLT"},
            { label : "SITLINK_GP", value : "SITLINK_GP", hospCode : "NLT"},
            { label : "AA_wks", value : "AA_wks", hospCode : "NLT"},
            { label : "CRAS_JAVA", value : "CRAS_JAVA", hospCode : "NLT"},
            { label : "EXTJS4_WKS", value : "EXTJS4_WKS", hospCode : "NLT"},
            { label : "CID_WKS", value : "CID_WKS", hospCode : "NLT"},
            { label : "WIN10", value : "WIN10", hospCode : "NLT"},
            { label : "WIN10_OPEN", value : "WIN10_OPEN", hospCode : "NLT"},
            { label : "TOUGHPAD-W10", value : "TOUGHPAD-W10", hospCode : "NLT"},
            { label : "AE_90TIMEOUT", value : "AE_90TIMEOUT", hospCode : "NLT"},
            { label : "CQMS_WKS", value : "CQMS_WKS", hospCode : "NLT"},
            { label : "CQMS_startup", value : "CQMS_startup", hospCode : "NLT"},
            { label : "EDGE_FILMLESS", value : "EDGE_FILMLESS", hospCode : "NLT"},
            { label : "MAP_M_DRIVE_NLT", value : "MAP_M_DRIVE_NLT", hospCode : "NLT"},
            { label : "AWE_VS_link", value : "AWE_VS_link", hospCode : "NLT"},
            { label : "AWE_VS_link_rollbcak", value : "AWE_VS_link_rollbcak", hospCode : "NLT"},
            { label : "cms_screen_config", value : "cms_screen_config", hospCode : "NLT"},
            { label : "offline_mar", value : "offline_mar", hospCode : "NLT"},
            { label : "check_ipmoe_iis", value : "check_ipmoe_iis", hospCode : "NLT"},
            { label : "remove_startup_shortcut", value : "remove_startup_shortcut", hospCode : "NLT"},
            { label : "WIN7_JAVA18", value : "WIN7_JAVA18", hospCode : "NLT"},
            { label : "CQMS_counter", value : "CQMS_counter", hospCode : "NLT"},
            { label : "check_cras_java", value : "check_cras_java", hospCode : "NLT"},
            { label : "BT-CONNECT", value : "BT-CONNECT", hospCode : "NLT"},
            { label : "HKICC_CMS", value : "HKICC_CMS", hospCode : "NLT"},
            { label : "HKICC_COW", value : "HKICC_COW", hospCode : "NLT"},
            { label : "HKICC_TABLET", value : "HKICC_TABLET", hospCode : "NLT"},
            { label : "HKICC_NB", value : "HKICC_NB", hospCode : "NLT"},
            { label : "inst_AEIS_web_12c", value : "inst_AEIS_web_12c", hospCode : "NLT"},
            { label : "scr_dist_jar", value : "scr_dist_jar", hospCode : "NLT"},
            { label : "AWE-GROUP", value : "AWE-GROUP", hospCode : "NLT"},
            { label : "sogou_pinyin", value : "sogou_pinyin", hospCode : "NLT"},
            { label : "sogou_pinyin_rollback", value : "sogou_pinyin_rollback", hospCode : "NLT"},
            { label : "ccp190", value : "ccp190", hospCode : "NLT"},
            { label : "cmschrome", value : "cmschrome", hospCode : "NLT"},
            { label : "CLW_OT", value : "CLW_OT", hospCode : "NLT"},
            { label : "OTPIS_OT", value : "OTPIS_OT", hospCode : "NLT"},
            { label : "CHROME_CQMS", value : "CHROME_CQMS", hospCode : "NLT"},
            { label : "ADB", value : "ADB", hospCode : "NLT"},
            { label : "SCRSAVE_OFF", value : "SCRSAVE_OFF", hospCode : "NLT"},
            { label : "eresus_ae", value : "eresus_ae", hospCode : "NLT"},
            { label : "MDE_WKS", value : "MDE_WKS", hospCode : "NLT"},
            { label : "MDE_WKS_BK", value : "MDE_WKS_BK", hospCode : "NLT"},
            { label : "Annalise_ailink", value : "Annalise_ailink", hospCode : "NLT"},
            { label : "WIN11", value : "WIN11", hospCode : "NLT"},
        ],
        index : 8,
    },
    {
        label: 'PMH', 
        options: [
            { label : "AE-WKS", value : "AE-WKS", hospCode : "PMH"},
            { label : "GCR-TEST", value : "GCR-TEST", hospCode : "PMH"},
            { label : "eot-gp", value : "eot-gp", hospCode : "PMH"},
            { label : "EOT-PRINT", value : "EOT-PRINT", hospCode : "PMH"},
            { label : "CMS-PHK", value : "CMS-PHK", hospCode : "PMH"},
            { label : "CMS-SKC", value : "CMS-SKC", hospCode : "PMH"},
            { label : "CMS-TCG", value : "CMS-TCG", hospCode : "PMH"},
            { label : "CMS-CHG", value : "CMS-CHG", hospCode : "PMH"},
            { label : "CMS-NKC", value : "CMS-NKC", hospCode : "PMH"},
            { label : "CMS-TYT", value : "CMS-TYT", hospCode : "PMH"},
            { label : "OT", value : "OT", hospCode : "PMH"},
            { label : "GCRSRE_PRINT", value : "GCRSRE_PRINT", hospCode : "PMH"},
            { label : "OPEN-WKS", value : "OPEN-WKS", hospCode : "PMH"},
            { label : "FILMLESS-GP", value : "FILMLESS-GP", hospCode : "PMH"},
            { label : "FILMLESS_EXT_GP", value : "FILMLESS_EXT_GP", hospCode : "PMH"},
            { label : "FILMLESS_EXT2_GP", value : "FILMLESS_EXT2_GP", hospCode : "PMH"},
            { label : "NS_CIS_GP", value : "NS_CIS_GP", hospCode : "PMH"},
            { label : "IP-MOE-H2", value : "IP-MOE-H2", hospCode : "PMH"},
            { label : "BDS_WKS", value : "BDS_WKS", hospCode : "PMH"},
            { label : "IP-MOE-MAR", value : "IP-MOE-MAR", hospCode : "PMH"},
            { label : "IP-MOE-G1", value : "IP-MOE-G1", hospCode : "PMH"},
            { label : "WIN7", value : "WIN7", hospCode : "PMH"},
            { label : "Web_rollback", value : "Web_rollback", hospCode : "PMH"},
            { label : "open_web_cms", value : "open_web_cms", hospCode : "PMH"},
            { label : "CQMS_WKS", value : "CQMS_WKS", hospCode : "PMH"},
            { label : "CRAS_JAVA", value : "CRAS_JAVA", hospCode : "PMH"},
            { label : "EXTJS4_WKS", value : "EXTJS4_WKS", hospCode : "PMH"},
            { label : "WIN10", value : "WIN10", hospCode : "PMH"},
            { label : "WIN10_OPEN", value : "WIN10_OPEN", hospCode : "PMH"},
            { label : "TOUGHPAD-W10", value : "TOUGHPAD-W10", hospCode : "PMH"},
            { label : "BT-CONNECT", value : "BT-CONNECT", hospCode : "PMH"},
            { label : "SOPD-MEM", value : "SOPD-MEM", hospCode : "PMH"},
            { label : "ICU-CIS", value : "ICU-CIS", hospCode : "PMH"},
            { label : "AE_90TIMEOUT", value : "AE_90TIMEOUT", hospCode : "PMH"},
            { label : "SCRSAVE_OFF", value : "SCRSAVE_OFF", hospCode : "PMH"},
            { label : "ICU_CIS_link_2", value : "ICU_CIS_link_2", hospCode : "PMH"},
            { label : "CQMS_startup", value : "CQMS_startup", hospCode : "PMH"},
            { label : "EDGE_FILMLESS", value : "EDGE_FILMLESS", hospCode : "PMH"},
            { label : "Uninstall_Firefox", value : "Uninstall_Firefox", hospCode : "PMH"},
            { label : "offline_mar", value : "offline_mar", hospCode : "PMH"},
            { label : "check_ipmoe_iis", value : "check_ipmoe_iis", hospCode : "PMH"},
            { label : "WIN7_JAVA18", value : "WIN7_JAVA18", hospCode : "PMH"},
            { label : "check_cras_java", value : "check_cras_java", hospCode : "PMH"},
            { label : "inst_AEIS_web_12c", value : "inst_AEIS_web_12c", hospCode : "PMH"},
            { label : "scr_dist_jar", value : "scr_dist_jar", hospCode : "PMH"},
            { label : "CCU_CIS_GP", value : "CCU_CIS_GP", hospCode : "PMH"},
            { label : "Cardisys_CIS_GP", value : "Cardisys_CIS_GP", hospCode : "PMH"},
            { label : "BDS_GP", value : "BDS_GP", hospCode : "PMH"},
            { label : "SITs-link", value : "SITs-link", hospCode : "PMH"},
            { label : "ccp190", value : "ccp190", hospCode : "PMH"},
            { label : "CID_WKS", value : "CID_WKS", hospCode : "PMH"},
            { label : "win7_jre6", value : "win7_jre6", hospCode : "PMH"},
            { label : "win10_jre6", value : "win10_jre6", hospCode : "PMH"},
            { label : "cmschrome", value : "cmschrome", hospCode : "PMH"},
            { label : "CLW_OT", value : "CLW_OT", hospCode : "PMH"},
            { label : "OTPIS_OT", value : "OTPIS_OT", hospCode : "PMH"},
            { label : "OTPIS_Mgt_Con", value : "OTPIS_Mgt_Con", hospCode : "PMH"},
            { label : "CHROME_CQMS", value : "CHROME_CQMS", hospCode : "PMH"},
            { label : "ICU_CIS_link_2_chrome", value : "ICU_CIS_link_2_chrome", hospCode : "PMH"},
            { label : "MDE_WKS", value : "MDE_WKS", hospCode : "PMH"},
            { label : "MDE_WKS_BK", value : "MDE_WKS_BK", hospCode : "PMH"},
            { label : "Annalise_ailink", value : "Annalise_ailink", hospCode : "PMH"},
            { label : "PICU_CIS", value : "PICU_CIS", hospCode : "PMH"},
            { label : "IPMOE_CIS", value : "IPMOE_CIS", hospCode : "PMH"},
            { label : "NHDU_CIS", value : "NHDU_CIS", hospCode : "PMH"},
        ],
        index : 9,
    },
    {
        label: 'YCH', 
        options: [
            { label : "eot-gp", value : "eot-gp", hospCode : "YCH"},
            { label : "YCH-FM", value : "YCH-FM", hospCode : "YCH"},
            { label : "CMS-LTR", value : "CMS-LTR", hospCode : "YCH"},
            { label : "CMS-MWY", value : "CMS-MWY", hospCode : "YCH"},
            { label : "GCRSRE_PRINT", value : "GCRSRE_PRINT", hospCode : "YCH"},
            { label : "OPEN-WKS", value : "OPEN-WKS", hospCode : "YCH"},
            { label : "WIN7", value : "WIN7", hospCode : "YCH"},
            { label : "FIL_LINK", value : "FIL_LINK", hospCode : "YCH"},
            { label : "OPD-AE", value : "OPD-AE", hospCode : "YCH"},
            { label : "FILMLESS_EXT", value : "FILMLESS_EXT", hospCode : "YCH"},
            { label : "NO_SCRNSAVER", value : "NO_SCRNSAVER", hospCode : "YCH"},
            { label : "run_cms_v2", value : "run_cms_v2", hospCode : "YCH"},
            { label : "BDS_WKS", value : "BDS_WKS", hospCode : "YCH"},
            { label : "IP-MOE-MAR", value : "IP-MOE-MAR", hospCode : "YCH"},
            { label : "IP-MOE-H2", value : "IP-MOE-H2", hospCode : "YCH"},
            { label : "IP-MOE-NB", value : "IP-MOE-NB", hospCode : "YCH"},
            { label : "IP-MOE-G1", value : "IP-MOE-G1", hospCode : "YCH"},
            { label : "web_rollback", value : "web_rollback", hospCode : "YCH"},
            { label : "open_web_cms", value : "open_web_cms", hospCode : "YCH"},
            { label : "CID_WKS", value : "CID_WKS", hospCode : "YCH"},
            { label : "REPIN_WKS", value : "REPIN_WKS", hospCode : "YCH"},
            { label : "KB-DEPLOY", value : "KB-DEPLOY", hospCode : "YCH"},
            { label : "NEW_CRAS", value : "NEW_CRAS", hospCode : "YCH"},
            { label : "CRAS_JAVA", value : "CRAS_JAVA", hospCode : "YCH"},
            { label : "EXTJS4_WKS", value : "EXTJS4_WKS", hospCode : "YCH"},
            { label : "7zip", value : "7zip", hospCode : "YCH"},
            { label : "WIN10", value : "WIN10", hospCode : "YCH"},
            { label : "open_web_cms_w10", value : "open_web_cms_w10", hospCode : "YCH"},
            { label : "TOUGHPAD-W10", value : "TOUGHPAD-W10", hospCode : "YCH"},
            { label : "AE_90TIMEOUT", value : "AE_90TIMEOUT", hospCode : "YCH"},
            { label : "ICU-CIS", value : "ICU-CIS", hospCode : "YCH"},
            { label : "CQMS_startup", value : "CQMS_startup", hospCode : "YCH"},
            { label : "CQMS_link", value : "CQMS_link", hospCode : "YCH"},
            { label : "EDGE_FILMLESS", value : "EDGE_FILMLESS", hospCode : "YCH"},
            { label : "Uninstall_Firefox", value : "Uninstall_Firefox", hospCode : "YCH"},
            { label : "offline_mar", value : "offline_mar", hospCode : "YCH"},
            { label : "check_ipmoe_iis", value : "check_ipmoe_iis", hospCode : "YCH"},
            { label : "WIN7_JAVA18", value : "WIN7_JAVA18", hospCode : "YCH"},
            { label : "check_cras_java", value : "check_cras_java", hospCode : "YCH"},
            { label : "inst_AEIS_web_12c", value : "inst_AEIS_web_12c", hospCode : "YCH"},
            { label : "scr_dist_jar", value : "scr_dist_jar", hospCode : "YCH"},
            { label : "YCH_CCU_CIS_link", value : "YCH_CCU_CIS_link", hospCode : "YCH"},
            { label : "ccp190", value : "ccp190", hospCode : "YCH"},
            { label : "win10_jre6", value : "win10_jre6", hospCode : "YCH"},
            { label : "cmschrome", value : "cmschrome", hospCode : "YCH"},
            { label : "CLW_OT", value : "CLW_OT", hospCode : "YCH"},
            { label : "OTPIS_OT", value : "OTPIS_OT", hospCode : "YCH"},
            { label : "CHROME_CQMS", value : "CHROME_CQMS", hospCode : "YCH"},
            { label : "MDE_WKS", value : "MDE_WKS", hospCode : "YCH"},
            { label : "MDE_WKS_BK", value : "MDE_WKS_BK", hospCode : "YCH"},
            { label : "Annalise_ailink", value : "Annalise_ailink", hospCode : "YCH"},
            { label : "Fundus_image", value : "Fundus_image", hospCode : "YCH"},
        ],
        index : 10,
    },
    {
        label: 'DKC', 
        options: [
            { label : "CMS-IP-W10", value : "CMS-IP-W10", hospCode : "DKC"},
            { label : "CMS-OP-W10", value : "CMS-OP-W10", hospCode : "DKC"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "DKC"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "DKC"},
            { label : "CQMS", value : "CQMS", hospCode : "DKC"},
            { label : "cms_edge_jre18_update_CLW_remove_LLW", value : "cms_edge_jre18_update_CLW_remove_LLW", hospCode : "DKC"},
            { label : "update_CLW_remove_LLW", value : "update_CLW_remove_LLW", hospCode : "DKC"},
            { label : "filmless_dual_mon", value : "filmless_dual_mon", hospCode : "DKC"},
            { label : "IPMOE", value : "IPMOE", hospCode : "DKC"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "DKC"},
            { label : "NEW-CRAS", value : "NEW-CRAS", hospCode : "DKC"},
            { label : "check_cras", value : "check_cras", hospCode : "DKC"},
            { label : "Citrix", value : "Citrix", hospCode : "DKC"},
            { label : "Chrome1", value : "Chrome1", hospCode : "DKC"},
            { label : "Chrome2", value : "Chrome2", hospCode : "DKC"},
        ],
        index : 11,
    },
    {
        label: 'FYK', 
        options: [
            { label : "CMS-IP-W10", value : "CMS-IP-W10", hospCode : "FYK"},
            { label : "CMS-OP-W10", value : "CMS-OP-W10", hospCode : "FYK"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "FYK"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "FYK"},
            { label : "cms_edge_jre18_update_CLW_remove_LLW", value : "cms_edge_jre18_update_CLW_remove_LLW", hospCode : "FYK"},
            { label : "update_CLW_remove_LLW", value : "update_CLW_remove_LLW", hospCode : "FYK"},
            { label : "filmless_dual_mon", value : "filmless_dual_mon", hospCode : "FYK"},
            { label : "IPMOE", value : "IPMOE", hospCode : "FYK"},
            { label : "NEW-CRAS", value : "NEW-CRAS", hospCode : "FYK"},
            { label : "check_cras", value : "check_cras", hospCode : "FYK"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "FYK"},
            { label : "Citrix", value : "Citrix", hospCode : "FYK"},
            { label : "Chrome1", value : "Chrome1", hospCode : "FYK"},
            { label : "Chrome2", value : "Chrome2", hospCode : "FYK"},        
        ],
        index : 12,
    },
    {
        label: 'GH', 
        options: [
            { label : "OT_WKS", value : "OT_WKS", hospCode : "GH"},
            { label : "CRAS-W10", value : "CRAS-W10", hospCode : "GH"},
            { label : "Citrix", value : "Citrix", hospCode : "GH"},
            { label : "CMS-IP-W7", value : "CMS-IP-W7", hospCode : "GH"},
            { label : "CMS-OP-W7", value : "CMS-OP-W7", hospCode : "GH"},
            { label : "CMS-IP-W10", value : "CMS-IP-W10", hospCode : "GH"},
            { label : "CMS-OP-W10", value : "CMS-OP-W10", hospCode : "GH"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "GH"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "GH"},
            { label : "update_CLW_remove_LLW", value : "update_CLW_remove_LLW", hospCode : "GH"},
            { label : "filmless_dual_mon", value : "filmless_dual_mon", hospCode : "GH"},
            { label : "IPMOE", value : "IPMOE", hospCode : "GH"},
            { label : "check_cras", value : "check_cras", hospCode : "GH"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "GH"},
            { label : "CQMSChrome", value : "CQMSChrome", hospCode : "GH"},
        ],
        index : 13,
    },
    {
        label: 'ML', 
        options: [
            { label : "CMS-IP-W10", value : "CMS-IP-W10", hospCode : "ML"},
            { label : "CMS-OP-W10", value : "CMS-OP-W10", hospCode : "ML"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "ML"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "ML"},
            { label : "cms_edge_jre18_update_CLW_remove_LLW", value : "cms_edge_jre18_update_CLW_remove_LLW", hospCode : "ML"},
            { label : "update_CLW_remove_LLW", value : "update_CLW_remove_LLW", hospCode : "ML"},
            { label : "filmless_dual_mon", value : "filmless_dual_mon", hospCode : "ML"},
            { label : "IPMOE", value : "IPMOE", hospCode : "ML"},
            { label : "NEW-CRAS", value : "NEW-CRAS", hospCode : "ML"},
            { label : "check_cras", value : "check_cras", hospCode : "ML"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "ML"},
            { label : "Citrix", value : "Citrix", hospCode : "ML"},
        ],
        index : 14,
    },
    {
        label: 'QMH', 
        options: [
            { label : "CMS-IP-W7", value : "CMS-IP-W7", hospCode : "QMH"},
            { label : "CMS-OP-W7", value : "CMS-OP-W7", hospCode : "QMH"},
            { label : "WPC-OPAS-HOST", value : "WPC-OPAS-HOST", hospCode : "QMH"},
            { label : "WPC-OP", value : "WPC-OP", hospCode : "QMH"},
            { label : "WPC-OPAS", value : "WPC-OPAS", hospCode : "QMH"},
            { label : "DUAL-CMS", value : "DUAL-CMS", hospCode : "QMH"},
            { label : "QMH-OPAS", value : "QMH-OPAS", hospCode : "QMH"},
            { label : "QMH-IP", value : "QMH-IP", hospCode : "QMH"},
            { label : "DIRECT-LLW", value : "DIRECT-LLW", hospCode : "QMH"},
            { label : "QMH-OPAS-HOST", value : "QMH-OPAS-HOST", hospCode : "QMH"},
            { label : "QMH-OP", value : "QMH-OP", hospCode : "QMH"},
            { label : "AEIS-INT", value : "AEIS-INT", hospCode : "QMH"},
            { label : "QMH-HOST", value : "QMH-HOST", hospCode : "QMH"},
            { label : "AJC-OP", value : "AJC-OP", hospCode : "QMH"},
            { label : "AJC-OPAS", value : "AJC-OPAS", hospCode : "QMH"},
            { label : "ALC-OP", value : "ALC-OP", hospCode : "QMH"},
            { label : "ALC-OPAS", value : "ALC-OPAS", hospCode : "QMH"},
            { label : "SYG-OPAS", value : "SYG-OPAS", hospCode : "QMH"},
            { label : "SYG-OP", value : "SYG-OP", hospCode : "QMH"},
            { label : "CDG-OP", value : "CDG-OP", hospCode : "QMH"},
            { label : "CDG-OPAS", value : "CDG-OPAS", hospCode : "QMH"},
            { label : "QMH-OPEN", value : "QMH-OPEN", hospCode : "QMH"},
            { label : "GCRS-TEST", value : "GCRS-TEST", hospCode : "QMH"},
            { label : "QMH-RIS-HOST", value : "QMH-RIS-HOST", hospCode : "QMH"},
            { label : "QMH-RIS", value : "QMH-RIS", hospCode : "QMH"},
            { label : "MANLINK", value : "MANLINK", hospCode : "QMH"},
            { label : "CMS-TRAIN", value : "CMS-TRAIN", hospCode : "QMH"},
            { label : "KTJ-OP", value : "KTJ-OP", hospCode : "QMH"},
            { label : "KTJ-OPAS", value : "KTJ-OPAS", hospCode : "QMH"},
            { label : "FILMLESS_WKS", value : "FILMLESS_WKS", hospCode : "QMH"},
            { label : "OT-SCREENSAVER", value : "OT-SCREENSAVER", hospCode : "QMH"},
            { label : "NEW-CRAS-W7", value : "NEW-CRAS-W7", hospCode : "QMH"},
            { label : "NEW-CRAS", value : "NEW-CRAS", hospCode : "QMH"},
            { label : "CID_WKS", value : "CID_WKS", hospCode : "QMH"},
            { label : "OT_WKS", value : "OT_WKS", hospCode : "QMH"},
            { label : "SRE", value : "SRE", hospCode : "QMH"},
            { label : "IPMOE", value : "IPMOE", hospCode : "QMH"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "QMH"},
            { label : "CMS-IP-W10", value : "CMS-IP-W10", hospCode : "QMH"},
            { label : "CMS-OP-W10", value : "CMS-OP-W10", hospCode : "QMH"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "QMH"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "QMH"},
            { label : "TYH_GO", value : "TYH_GO", hospCode : "QMH"},
            { label : "update_CLW_remove_LLW", value : "update_CLW_remove_LLW", hospCode : "QMH"},
            { label : "CQMS", value : "CQMS", hospCode : "QMH"},
            { label : "CQMSChrome", value : "CQMSChrome", hospCode : "QMH"},
            { label : "filmless_dual_mon", value : "filmless_dual_mon", hospCode : "QMH"},
            { label : "check_cras", value : "check_cras", hospCode : "QMH"},
            { label : "CLW_OT_DA_link", value : "CLW_OT_DA_link", hospCode : "QMH"},
            { label : "OTPIS_DA_link", value : "OTPIS_DA_link", hospCode : "QMH"},
            { label : "PNICU_CIS_WKS", value : "PNICU_CIS_WKS", hospCode : "QMH"},
            { label : "AEIS", value : "AEIS", hospCode : "QMH"},
            { label : "Citrix", value : "Citrix", hospCode : "QMH"},
        ],
        index : 15,
    },
    {
        label: 'TWH', 
        options: [
            { label : "CMS-IP-XP", value : "CMS-IP-XP", hospCode : "TWH"},
            { label : "TWH-OPEN", value : "TWH-OPEN", hospCode : "TWH"},
            { label : "TWH-OT", value : "TWH-OT", hospCode : "TWH"},
            { label : "TWH-CLOSE", value : "TWH-CLOSE", hospCode : "TWH"},
            { label : "TWH-RIS-HOST", value : "TWH-RIS-HOST", hospCode : "TWH"},
            { label : "CMS-OP-W2K", value : "CMS-OP-W2K", hospCode : "TWH"},
            { label : "CMS-OP-XP", value : "CMS-OP-XP", hospCode : "TWH"},
            { label : "TWH-OPAS-HOST", value : "TWH-OPAS-HOST", hospCode : "TWH"},
            { label : "TWH-IPAS-HOST", value : "TWH-IPAS-HOST", hospCode : "TWH"},
            { label : "CMS-IP-W7", value : "CMS-IP-W7", hospCode : "TWH"},
            { label : "CMS-IP-W10", value : "CMS-IP-W10", hospCode : "TWH"},
            { label : "CMS-OP-W10", value : "CMS-OP-W10", hospCode : "TWH"},
            { label : "CMS-IP-W11", value : "CMS-IP-W11", hospCode : "TWH"},
            { label : "CMS-OP-W11", value : "CMS-OP-W11", hospCode : "TWH"},
            { label : "NEW-CRAS", value : "NEW-CRAS", hospCode : "TWH"},
            { label : "cms_edge_jre18_update_CLW_remove_LLW", value : "cms_edge_jre18_update_CLW_remove_LLW", hospCode : "TWH"},
            { label : "update_CLW_remove_LLW", value : "update_CLW_remove_LLW", hospCode : "TWH"},
            { label : "filmless_dual_mon", value : "filmless_dual_mon", hospCode : "TWH"},
            { label : "IPMOE", value : "IPMOE", hospCode : "TWH"},
            { label : "IPMOE_Training", value : "IPMOE_Training", hospCode : "TWH"},
            { label : "IPMOE_OFFLINE_MAR", value : "IPMOE_OFFLINE_MAR", hospCode : "TWH"},
            { label : "check_cras", value : "check_cras", hospCode : "TWH"},
            { label : "CQMSChrome", value : "CQMSChrome", hospCode : "TWH"},
        ],
        index : 16,
    },
    {
        label: 'AHN', 
        options: [
            { label : "MDE", value : "MDE", hospCode : "AHN"},
            { label : "CQMS_Chrome_Call", value : "CQMS_Chrome_Call", hospCode : "AHN"},
            { label : "OPH_chrome_epr", value : "OPH_chrome_epr", hospCode : "AHN"},
            { label : "Package_CQMS", value : "Package_CQMS", hospCode : "AHN"},
            { label : "CQMS_AEDTicketService", value : "CQMS_AEDTicketService", hospCode : "AHN"},
            { label : "Package_CQMS_counter", value : "Package_CQMS_counter", hospCode : "AHN"},
            { label : "CIS-ICU-WKS", value : "CIS-ICU-WKS", hospCode : "AHN"},
            { label : "ICU-WKS_OTHER", value : "ICU-WKS_OTHER", hospCode : "AHN"},
            { label : "DATA-DOWNLOAD", value : "DATA-DOWNLOAD", hospCode : "AHN"},
            { label : "CID-ERS-WKS", value : "CID-ERS-WKS", hospCode : "AHN"},
            { label : "BDS_downtime", value : "BDS_downtime", hospCode : "AHN"},
            { label : "IPMOE_downtimesystem", value : "IPMOE_downtimesystem", hospCode : "AHN"},
            { label : "IPMOE_TP", value : "IPMOE_TP", hospCode : "AHN"},
            { label : "IPMOE_WS_NB", value : "IPMOE_WS_NB", hospCode : "AHN"},
            { label : "OT-EXT-DA", value : "OT-EXT-DA", hospCode : "AHN"},
            { label : "SRE", value : "SRE", hospCode : "AHN"},
            { label : "WIRELESS_GP", value : "WIRELESS_GP", hospCode : "AHN"},
            { label : "CMS-LRR", value : "CMS-LRR", hospCode : "AHN"},
            { label : "CMS-IP", value : "CMS-IP", hospCode : "AHN"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "AHN"},
            { label : "CMS-INT", value : "CMS-INT", hospCode : "AHN"},
            { label : "CMS-TEST", value : "CMS-TEST", hospCode : "AHN"},
            { label : "AEIS-INT", value : "AEIS-INT", hospCode : "AHN"},
            { label : "W2K-IP", value : "W2K-IP", hospCode : "AHN"},
            { label : "W2K-OP", value : "W2K-OP", hospCode : "AHN"},
            { label : "W2K-OPAS-INT", value : "W2K-OPAS-INT", hospCode : "AHN"},
            { label : "W2K-INT", value : "W2K-INT", hospCode : "AHN"},
            { label : "LIS-INT", value : "LIS-INT", hospCode : "AHN"},
            { label : "CRAS", value : "CRAS", hospCode : "AHN"},
            { label : "W7-CRAS", value : "W7-CRAS", hospCode : "AHN"},
            { label : "CRAS_2018", value : "CRAS_2018", hospCode : "AHN"},
            { label : "CRAS_2018_USB", value : "CRAS_2018_USB", hospCode : "AHN"},
            { label : "CMS-WSC", value : "CMS-WSC", hospCode : "AHN"},
            { label : "CMS-TPJ", value : "CMS-TPJ", hospCode : "AHN"},
            { label : "WXP-IP", value : "WXP-IP", hospCode : "AHN"},
            { label : "WXP-OP", value : "WXP-OP", hospCode : "AHN"},
            { label : "WXP-WSC", value : "WXP-WSC", hospCode : "AHN"},
            { label : "WXP-TPJ", value : "WXP-TPJ", hospCode : "AHN"},
            { label : "WXP-INT", value : "WXP-INT", hospCode : "AHN"},
            { label : "CMS-MO", value : "CMS-MO", hospCode : "AHN"},
            { label : "TIMING_GP", value : "TIMING_GP", hospCode : "AHN"},
            { label : "Package_GP01", value : "Package_GP01", hospCode : "AHN"},
            { label : "Package_GP02", value : "Package_GP02", hospCode : "AHN"},
            { label : "Package_GP03", value : "Package_GP03", hospCode : "AHN"},
            { label : "Package_GP04", value : "Package_GP04", hospCode : "AHN"},
            { label : "Package_GP05", value : "Package_GP05", hospCode : "AHN"},
            { label : "Package_GP06", value : "Package_GP06", hospCode : "AHN"},
            { label : "Package_GP07", value : "Package_GP07", hospCode : "AHN"},
            { label : "Package_GP08", value : "Package_GP08", hospCode : "AHN"},
            { label : "Package_GP09", value : "Package_GP09", hospCode : "AHN"},
            { label : "Package_GP10", value : "Package_GP10", hospCode : "AHN"},
            { label : "WIN10_DOT4_PRINTER_WKS", value : "WIN10_DOT4_PRINTER_WKS", hospCode : "AHN"},
            { label : "AE_Smart_Card", value : "AE_Smart_Card", hospCode : "AHN"},
            { label : "AE_wks_scrnsave", value : "AE_wks_scrnsave", hospCode : "AHN"},
        ],
        index : 17,
    },
    {
        label: 'BBH', 
        options: [
            { label : "install_group0", value : "install_group0", hospCode : "BBH"},
            { label : "install_group1", value : "install_group1", hospCode : "BBH"},
            { label : "CRAS_2018_USB", value : "CRAS_2018_USB", hospCode : "BBH"},
            { label : "DATA-DOWNLOAD", value : "DATA-DOWNLOAD", hospCode : "BBH"},
            { label : "SRE", value : "SRE", hospCode : "BBH"},
            { label : "IPMOE_TP", value : "IPMOE_TP", hospCode : "BBH"},
            { label : "IPMOE_downtimesystem", value : "IPMOE_downtimesystem", hospCode : "BBH"},
            { label : "BDS_downtime", value : "BDS_downtime", hospCode : "BBH"},
            { label : "WXP-IP", value : "WXP-IP", hospCode : "BBH"},
            { label : "WXP-OP", value : "WXP-OP", hospCode : "BBH"},
            { label : "WIN10_DOT4_PRINTER_WKS", value : "WIN10_DOT4_PRINTER_WKS", hospCode : "BBH"},
            { label : "WIN7_JRE", value : "WIN7_JRE", hospCode : "BBH"},
        ],
        index : 18,
    },
    {
        label: 'SCH', 
        options: [
            { label : "MDE", value : "MDE", hospCode : "SCH"},
            { label : "install_group0", value : "install_group0", hospCode : "SCH"},
            { label : "install_group1", value : "install_group1", hospCode : "SCH"},
            { label : "install_group2", value : "install_group2", hospCode : "SCH"},
            { label : "CRAS_2018_USB", value : "CRAS_2018_USB", hospCode : "SCH"},
            { label : "DATA-DOWNLOAD", value : "DATA-DOWNLOAD", hospCode : "SCH"},
            { label : "SRE", value : "SRE", hospCode : "SCH"},
            { label : "IPMOE_TP", value : "IPMOE_TP", hospCode : "SCH"},
            { label : "IPMOE_downtimesystem", value : "IPMOE_downtimesystem", hospCode : "SCH"},
            { label : "BDS_downtime", value : "BDS_downtime", hospCode : "SCH"},
            { label : "WXP-IP", value : "WXP-IP", hospCode : "SCH"},
            { label : "WXP-OP", value : "WXP-OP", hospCode : "SCH"},
            { label : "WIN10_DOT4_PRINTER_WKS", value : "WIN10_DOT4_PRINTER_WKS", hospCode : "SCH"},
            { label : "WIN7_JRE", value : "WIN7_JRE", hospCode : "SCH"},
        ],
        index : 19,
    },
    {
        label: 'NDH', 
        options: [
            { label : "MDE", value : "MDE", hospCode : "NDH"},
            { label : "CQMS_Chrome_Call", value : "CQMS_Chrome_Call", hospCode : "NDH"},
            { label : "CIS-ICU-WKS", value : "CIS-ICU-WKS", hospCode : "NDH"},
            { label : "Package_CQMS", value : "Package_CQMS", hospCode : "NDH"},
            { label : "CQMS_AEDTicketService", value : "CQMS_AEDTicketService", hospCode : "NDH"},
            { label : "Package_CQMS_counter", value : "Package_CQMS_counter", hospCode : "NDH"},
            { label : "DATA-DOWNLOAD", value : "DATA-DOWNLOAD", hospCode : "NDH"},
            { label : "CID-ERS-WKS", value : "CID-ERS-WKS", hospCode : "NDH"},
            { label : "CID-ERS-WKS_WEB", value : "CID-ERS-WKS_WEB", hospCode : "NDH"},
            { label : "BDS_chrome_link", value : "BDS_chrome_link", hospCode : "NDH"},
            { label : "BDS_downtime", value : "BDS_downtime", hospCode : "NDH"},
            { label : "IPMOE_downtimesystem", value : "IPMOE_downtimesystem", hospCode : "NDH"},
            { label : "IPMOE_WS_NB", value : "IPMOE_WS_NB", hospCode : "NDH"},
            { label : "IPMOE_DEMO", value : "IPMOE_DEMO", hospCode : "NDH"},
            { label : "IPMOE_TP", value : "IPMOE_TP", hospCode : "NDH"},
            { label : "OT-EXT-DA", value : "OT-EXT-DA", hospCode : "NDH"},
            { label : "OT-PIS-DA", value : "OT-PIS-DA", hospCode : "NDH"},
            { label : "SRE", value : "SRE", hospCode : "NDH"},
            { label : "WIRELESS_GP", value : "WIRELESS_GP", hospCode : "NDH"},
            { label : "WXP-IP", value : "WXP-IP", hospCode : "NDH"},
            { label : "WXP-LRR", value : "WXP-LRR", hospCode : "NDH"},
            { label : "WXP-OP", value : "WXP-OP", hospCode : "NDH"},
            { label : "WXP-AEIS-INT", value : "WXP-AEIS-INT", hospCode : "NDH"},
            { label : "WXP-FLC", value : "WXP-FLC", hospCode : "NDH"},
            { label : "WXP-NSW", value : "WXP-NSW", hospCode : "NDH"},
            { label : "WXP-STK", value : "WXP-STK", hospCode : "NDH"},
            { label : "WXP-TKL", value : "WXP-TKL", hospCode : "NDH"},
            { label : "W2K-LRR", value : "W2K-LRR", hospCode : "NDH"},
            { label : "W2K-OPAS-INT", value : "W2K-OPAS-INT", hospCode : "NDH"},
            { label : "W2K-LIS-INT", value : "W2K-LIS-INT", hospCode : "NDH"},
            { label : "W2K-RIS-INT", value : "W2K-RIS-INT", hospCode : "NDH"},
            { label : "W2K-AEIS-INT", value : "W2K-AEIS-INT", hospCode : "NDH"},
            { label : "W2K-IP", value : "W2K-IP", hospCode : "NDH"},
            { label : "W2K-OP", value : "W2K-OP", hospCode : "NDH"},
            { label : "TRAINING", value : "TRAINING", hospCode : "NDH"},
            { label : "CMS-LRR", value : "CMS-LRR", hospCode : "NDH"},
            { label : "LIS-INT", value : "LIS-INT", hospCode : "NDH"},
            { label : "RIS-INT", value : "RIS-INT", hospCode : "NDH"},
            { label : "CMS-IP", value : "CMS-IP", hospCode : "NDH"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "NDH"},
            { label : "AEIS-INT", value : "AEIS-INT", hospCode : "NDH"},
            { label : "CRAS", value : "CRAS", hospCode : "NDH"},
            { label : "W7-CRAS", value : "W7-CRAS", hospCode : "NDH"},
            { label : "CRAS_2018", value : "CRAS_2018", hospCode : "NDH"},
            { label : "CRAS_2018_USB", value : "CRAS_2018_USB", hospCode : "NDH"},
            { label : "CMS-MO", value : "CMS-MO", hospCode : "NDH"},
            { label : "TIMING_GP", value : "TIMING_GP", hospCode : "NDH"},
            { label : "Package_GP01", value : "Package_GP01", hospCode : "NDH"},
            { label : "Package_GP02", value : "Package_GP02", hospCode : "NDH"},
            { label : "Package_GP03", value : "Package_GP03", hospCode : "NDH"},
            { label : "Package_GP04", value : "Package_GP04", hospCode : "NDH"},
            { label : "Package_GP05", value : "Package_GP05", hospCode : "NDH"},
            { label : "Package_GP06", value : "Package_GP06", hospCode : "NDH"},
            { label : "Package_GP07", value : "Package_GP07", hospCode : "NDH"},
            { label : "Package_GP08", value : "Package_GP08", hospCode : "NDH"},
            { label : "Package_GP09", value : "Package_GP09", hospCode : "NDH"},
            { label : "Package_GP10", value : "Package_GP10", hospCode : "NDH"},
            { label : "WIN10_DOT4_PRINTER_WKS", value : "WIN10_DOT4_PRINTER_WKS", hospCode : "NDH"},
            { label : "AE_wks_scrnsave", value : "AE_wks_scrnsave", hospCode : "NDH"},
            { label : "AE_Smart_Card", value : "AE_Smart_Card", hospCode : "NDH"},
            { label : "OT_direct_access_new", value : "OT_direct_access_new", hospCode : "NDH"},
            { label : "reinstall_w11", value : "reinstall_w11", hospCode : "NDH"},
        ],
        index : 20,
    },
    {
        label: 'PWH', 
        options: [
            { label : "reinstall_w11", value : "reinstall_w11", hospCode : "PWH"},
            { label : "MDE", value : "MDE", hospCode : "PWH"},
            { label : "CQMS_Chrome_Call", value : "CQMS_Chrome_Call", hospCode : "PWH"},
            { label : "IPMOE_WS_NB", value : "IPMOE_WS_NB", hospCode : "PWH"},
            { label : "CIS-ICU-WKS", value : "CIS-ICU-WKS", hospCode : "PWH"},
            { label : "IPMOE_downtimedrill", value : "IPMOE_downtimedrill", hospCode : "PWH"},
            { label : "IPMOE_offline_admin_drill", value : "IPMOE_offline_admin_drill", hospCode : "PWH"},
            { label : "BDS_downtime", value : "BDS_downtime", hospCode : "PWH"},
            { label : "BDS_chrome_link", value : "BDS_chrome_link", hospCode : "PWH"},
            { label : "CHEMO_OFFLINE", value : "CHEMO_OFFLINE", hospCode : "PWH"},
            { label : "CHEMO_CLINIC", value : "CHEMO_CLINIC", hospCode : "PWH"},
            { label : "IPMOE_downtimesystem", value : "IPMOE_downtimesystem", hospCode : "PWH"},
            { label : "IPMOE_TP", value : "IPMOE_TP", hospCode : "PWH"},
            { label : "DATA-DOWNLOAD", value : "DATA-DOWNLOAD", hospCode : "PWH"},
            { label : "OT-EXT-DA", value : "OT-EXT-DA", hospCode : "PWH"},
            { label : "OT-PIS-DA", value : "OT-PIS-DA", hospCode : "PWH"},
            { label : "SRE_LNK", value : "SRE_LNK", hospCode : "PWH"},
            { label : "SRE", value : "SRE", hospCode : "PWH"},
            { label : "WIRELESS_GP", value : "WIRELESS_GP", hospCode : "PWH"},
            { label : "WXP-IP", value : "WXP-IP", hospCode : "PWH"},
            { label : "WXP-IP-I", value : "WXP-IP-I", hospCode : "PWH"},
            { label : "WXP-OP", value : "WXP-OP", hospCode : "PWH"},
            { label : "WXP-LRR", value : "WXP-LRR", hospCode : "PWH"},
            { label : "WXP-OP-I", value : "WXP-OP-I", hospCode : "PWH"},
            { label : "WXP-AE-INT", value : "WXP-AE-INT", hospCode : "PWH"},
            { label : "WXP-MOS", value : "WXP-MOS", hospCode : "PWH"},
            { label : "WXP-LYG", value : "WXP-LYG", hospCode : "PWH"},
            { label : "WXP-YCK", value : "WXP-YCK", hospCode : "PWH"},
            { label : "WXP-STG", value : "WXP-STG", hospCode : "PWH"},
            { label : "CRAS_2018", value : "CRAS_2018", hospCode : "PWH"},
            { label : "CRAS_2018_USB", value : "CRAS_2018_USB", hospCode : "PWH"},
            { label : "W2K-OPAS-INT", value : "W2K-OPAS-INT", hospCode : "PWH"},
            { label : "RIS-INT", value : "RIS-INT", hospCode : "PWH"},
            { label : "LIS-INT", value : "LIS-INT", hospCode : "PWH"},
            { label : "CMS-LYG", value : "CMS-LYG", hospCode : "PWH"},
            { label : "CMS-YCK", value : "CMS-YCK", hospCode : "PWH"},
            { label : "CMS-MOS", value : "CMS-MOS", hospCode : "PWH"},
            { label : "CMS-STG", value : "CMS-STG", hospCode : "PWH"},
            { label : "CMS-MO", value : "CMS-MO", hospCode : "PWH"},
            { label : "AEIS_GP", value : "AEIS_GP", hospCode : "PWH"},
            { label : "OTMS_GP", value : "OTMS_GP", hospCode : "PWH"},
            { label : "TIMING_GP", value : "TIMING_GP", hospCode : "PWH"},
            { label : "TIMING_Y_GP", value : "TIMING_Y_GP", hospCode : "PWH"},
            { label : "KF210_update", value : "KF210_update", hospCode : "PWH"},
            { label : "Package_GP01", value : "Package_GP01", hospCode : "PWH"},
            { label : "Package_GP02", value : "Package_GP02", hospCode : "PWH"},
            { label : "Package_GP03", value : "Package_GP03", hospCode : "PWH"},
            { label : "Package_GP04", value : "Package_GP04", hospCode : "PWH"},
            { label : "Package_GP05", value : "Package_GP05", hospCode : "PWH"},
            { label : "Package_GP06", value : "Package_GP06", hospCode : "PWH"},
            { label : "Package_GP07", value : "Package_GP07", hospCode : "PWH"},
            { label : "Package_GP08", value : "Package_GP08", hospCode : "PWH"},
            { label : "Package_GP09", value : "Package_GP09", hospCode : "PWH"},
            { label : "Package_GP10", value : "Package_GP10", hospCode : "PWH"},
            { label : "CQMS_AEDTicketService", value : "CQMS_AEDTicketService", hospCode : "PWH"},
            { label : "Package_CQMS_counter", value : "Package_CQMS_counter", hospCode : "PWH"},
            { label : "Package_CQMS", value : "Package_CQMS", hospCode : "PWH"},
            { label : "FIRST_BATCH", value : "FIRST_BATCH", hospCode : "PWH"},
            { label : "WIN10_DOT4_PRINTER_WKS", value : "WIN10_DOT4_PRINTER_WKS", hospCode : "PWH"},
            { label : "AE_wks_scrnsave", value : "AE_wks_scrnsave", hospCode : "PWH"},
            { label : "AE_Smart_Card", value : "AE_Smart_Card", hospCode : "PWH"},
            { label : "Smart_card_ward", value : "Smart_card_ward", hospCode : "PWH"},
        ],
        index : 21,
    },
    {
        label: 'SH', 
        options: [
            { label : "MDE", value : "MDE", hospCode : "SH"},
            { label : "CRAS_2018_USB", value : "CRAS_2018_USB", hospCode : "SH"},
            { label : "DATA-DOWNLOAD", value : "DATA-DOWNLOAD", hospCode : "SH"},
            { label : "SRE", value : "SRE", hospCode : "SH"},
            { label : "IPMOE_TP", value : "IPMOE_TP", hospCode : "SH"},
            { label : "IPMOE_downtimesystem", value : "IPMOE_downtimesystem", hospCode : "SH"},
            { label : "BDS_downtime", value : "BDS_downtime", hospCode : "SH"},
            { label : "BDS_downtime2", value : "BDS_downtime2", hospCode : "SH"},
            { label : "WXP-IP", value : "WXP-IP", hospCode : "SH"},
            { label : "WXP-OP", value : "WXP-OP", hospCode : "SH"},
            { label : "install_group0", value : "install_group0", hospCode : "SH"},
            { label : "install_group1", value : "install_group1", hospCode : "SH"},
            { label : "install_group2", value : "install_group2", hospCode : "SH"},
            { label : "WIN10_DOT4_PRINTER_WKS", value : "WIN10_DOT4_PRINTER_WKS", hospCode : "SH"},
            { label : "WIN7_JRE", value : "WIN7_JRE", hospCode : "SH"},
        ],
        index : 22,
    },
    {
        label: 'TPH', 
        options: [
            { label : "DATA-DOWNLOAD", value : "DATA-DOWNLOAD", hospCode : "TPH"},
            { label : "MDE", value : "MDE", hospCode : "TPH"},
            { label : "SRE", value : "SRE", hospCode : "TPH"},
            { label : "CRAS_2018_USB", value : "CRAS_2018_USB", hospCode : "TPH"},
            { label : "IPMOE_TP", value : "IPMOE_TP", hospCode : "TPH"},
            { label : "BDS_downtime", value : "BDS_downtime", hospCode : "TPH"},
            { label : "IPMOE_downtimesystem", value : "IPMOE_downtimesystem", hospCode : "TPH"},
            { label : "WIRELESS_GP", value : "WIRELESS_GP", hospCode : "TPH"},
            { label : "WXP-IP", value : "WXP-IP", hospCode : "TPH"},
            { label : "WXP-OP", value : "WXP-OP", hospCode : "TPH"},
            { label : "CMS-IP", value : "CMS-IP", hospCode : "TPH"},
            { label : "CMS-OP", value : "CMS-OP", hospCode : "TPH"},
            { label : "W2K-IP", value : "W2K-IP", hospCode : "TPH"},
            { label : "W2K-OP", value : "W2K-OP", hospCode : "TPH"},
            { label : "install_group0", value : "install_group0", hospCode : "TPH"},
            { label : "install_group1", value : "install_group1", hospCode : "TPH"},
            { label : "install_group2", value : "install_group2", hospCode : "TPH"},
            { label : "WIN10_DOT4_PRINTER_WKS", value : "WIN10_DOT4_PRINTER_WKS", hospCode : "TPH"},
            { label : "AE_wks_scrnsave", value : "AE_wks_scrnsave", hospCode : "TPH"},
            { label : "WIN7_JRE", value : "WIN7_JRE", hospCode : "TPH"},
        ],
        index : 23,
    },
]